Add an option to define the name that will be used to create the link
smilingrobots/wpv pull request #1
Opened 2018-10-20 21:06 UTC by wvega

I had modified the previous version of the script so that `vp create public_html next.plugin` would:

* Install WordPress on the `public_html` directory inside the current directory and
* Create a Valet link for the `next.plugin.test` domain pointing to that `public_html` directory.

I added the `-p <projectname>` option to achieve the same goal using `wpv -c -p next.awpcp -d public_html`.

I also modified the script to allow dots (`.`) on project names and replace both `.` and `-` with `_` on database names. Previously trying to use the script inside a directory with `-` on the name, such as `test-plugin`, would try to create a `test-plugin` database and fail.

If being able to configure the project name sounds like something we want, we could avoid adding a new option by making the `-s` option accept the project name (or site name) and always assume that the current directory is the source/project directory.

2018-11-13 13:16 UTC, jorgeatorres requested changes
Just one minor change and this is ready to go.

2018-11-13 13:16 UTC, jorgeatorres commented on wpv.sh
> +while getopts "cp:s:d:hn" argname; do
The getopts string must start with `:` so that getopts operates in "silent" mode.

```suggestion
while getopts ":cp:s:d:hn" argname; do
```

2018-11-13 13:20 UTC, jorgeatorres commented
> If being able to configure the project name sounds like something we want, we could avoid adding a new option by making the -s option accept the project name (or site name) and always assume that the current directory is the source/project directory.

I'm not against this. It actually makes sense since you can just `cd` into the desired directory (if needed). I'll merge this once the `getopts` thingy is fixed, but if you want to include this new change too, that'd be great.

2018-11-13 14:28 UTC, wvega commented on wpv.sh
> +while getopts "cp:s:d:hn" argname; do
Fixed. Thanks for the suggestion :D

2018-11-13 14:29 UTC, wvega commented
@jorgeatorres I just pushed a commit to remove `-p` option and start using `-s` to define the name of the site instead. Please take a look at the [new modifications](https://github.com/smilingrobots/wpv/pull/1/commits/28a01d5a7d4dee584fa8fe550fdf3af07643eaeb).

2019-03-02 16:31 UTC, jorgeatorres approved these changes
LGTM 💯.

2019-03-02 16:31 UTC, merged